### ISSUE TITLE
Half-body train

### ISSUE THREAD

**Issue by juanmarin96** [RuiLiFeng/Deep-Generative-Projection#4]
Hi, could the model be trained with a custom dataset with images like VTON dataset, it means, half body images where the face is show up?. Thanks for share this repo with us.

**Comment by RuiLiFeng** [comment]
VTON dataset may be a bit small for training this model. You may not be able to get a stable result with it. If the data volume is more extensive than 100k, I think it could succeed. 

For a custom dataset, you may need high-quality and clean data, ie, images with clean backgrounds and people aligned in the middle. Otherwise, the training may not succeed as in typical StyleGANs.

I am now uploading the ESF dataset to the Onedrive. It may be soon that you can acquire and train the model with this dataset.
