### ISSUE TITLE
Test with bottom clothes

### ISSUE THREAD

**Issue by omaraga12** [RuiLiFeng/Deep-Generative-Projection#9]
Hello, this work is awesome.
Is there a way to test o retrain this work usin bottom clothes like pants?

**Comment by RuiLiFeng** [comment]
Sorry currently only the pretrained StyleGAN for upper clothes is provided, thus we may only test it on upper clothes. But if you have pretrained StyleGAN for bottom clothes, there should be no difficult in applying this method.

**Comment by omaraga12** [comment]
> Thank you for your response. I have a dataset of bottom clothes. Must I change something on the networks or something like that for the training with bottom clothes?

**Comment by RuiLiFeng** [comment]
Due to our experience, you need to change nothing on the network architecture if your images are 512x512, clean, and center-aligned. For other resolutions, you may use the corresponding parameter settings in the StyleGAN2 official repo (https://github.com/NVlabs/stylegan2). If the data is insufficient (<around 10k), you may consider using data augmentation methods like StyleGAN-Ada (https://github.com/NVlabs/stylegan2-ada-pytorch).

**Comment by omaraga12** [comment]
> Due to our experience, you need to change nothing on the network architecture if your images are 512x512, clean, and center-aligned. For other resolutions, you may use the corresponding parameter settings in the StyleGAN2 official repo (https://github.com/NVlabs/stylegan2). If the data is insufficient (<around 10k), you may consider using data augmentation methods like StyleGAN-Ada (https://github.com/NVlabs/stylegan2-ada-pytorch).

Great, thank you so much
